POST http://localhost:3000/store
content-type: application/json

{
    "name": "Coco1 Dog",
    "jobs": [{"title": "jumpp", "position": "stage 1"}, {"title": "runn", "position": "stage 4"}]
}
###

GET http://localhost:3000/get